# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/linux/Desktop/my/code/sunqiang/Sun Qiang Project/pyOrthoDr"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/linux/Desktop/my/code/sunqiang/Sun Qiang Project/pyOrthoDr"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/linux/Desktop/my/code/sunqiang/Sun Qiang Project/pyOrthoDr/CMakeFiles" "/Users/linux/Desktop/my/code/sunqiang/Sun Qiang Project/pyOrthoDr/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/linux/Desktop/my/code/sunqiang/Sun Qiang Project/pyOrthoDr/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cpp_exports

# Build rule for target.
cpp_exports: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpp_exports
.PHONY : cpp_exports

# fast build rule for target.
cpp_exports/fast:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/build
.PHONY : cpp_exports/fast

cpp/cpp_exports.o: cpp/cpp_exports.cpp.o

.PHONY : cpp/cpp_exports.o

# target to build an object file
cpp/cpp_exports.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/cpp_exports.cpp.o
.PHONY : cpp/cpp_exports.cpp.o

cpp/cpp_exports.i: cpp/cpp_exports.cpp.i

.PHONY : cpp/cpp_exports.i

# target to preprocess a source file
cpp/cpp_exports.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/cpp_exports.cpp.i
.PHONY : cpp/cpp_exports.cpp.i

cpp/cpp_exports.s: cpp/cpp_exports.cpp.s

.PHONY : cpp/cpp_exports.s

# target to generate assembly for a file
cpp/cpp_exports.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/cpp_exports.cpp.s
.PHONY : cpp/cpp_exports.cpp.s

cpp/gen_solver.o: cpp/gen_solver.cpp.o

.PHONY : cpp/gen_solver.o

# target to build an object file
cpp/gen_solver.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/gen_solver.cpp.o
.PHONY : cpp/gen_solver.cpp.o

cpp/gen_solver.i: cpp/gen_solver.cpp.i

.PHONY : cpp/gen_solver.i

# target to preprocess a source file
cpp/gen_solver.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/gen_solver.cpp.i
.PHONY : cpp/gen_solver.cpp.i

cpp/gen_solver.s: cpp/gen_solver.cpp.s

.PHONY : cpp/gen_solver.s

# target to generate assembly for a file
cpp/gen_solver.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/gen_solver.cpp.s
.PHONY : cpp/gen_solver.cpp.s

cpp/reg_local_solver.o: cpp/reg_local_solver.cpp.o

.PHONY : cpp/reg_local_solver.o

# target to build an object file
cpp/reg_local_solver.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/reg_local_solver.cpp.o
.PHONY : cpp/reg_local_solver.cpp.o

cpp/reg_local_solver.i: cpp/reg_local_solver.cpp.i

.PHONY : cpp/reg_local_solver.i

# target to preprocess a source file
cpp/reg_local_solver.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/reg_local_solver.cpp.i
.PHONY : cpp/reg_local_solver.cpp.i

cpp/reg_local_solver.s: cpp/reg_local_solver.cpp.s

.PHONY : cpp/reg_local_solver.s

# target to generate assembly for a file
cpp/reg_local_solver.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/reg_local_solver.cpp.s
.PHONY : cpp/reg_local_solver.cpp.s

cpp/reg_phd_solver.o: cpp/reg_phd_solver.cpp.o

.PHONY : cpp/reg_phd_solver.o

# target to build an object file
cpp/reg_phd_solver.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/reg_phd_solver.cpp.o
.PHONY : cpp/reg_phd_solver.cpp.o

cpp/reg_phd_solver.i: cpp/reg_phd_solver.cpp.i

.PHONY : cpp/reg_phd_solver.i

# target to preprocess a source file
cpp/reg_phd_solver.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/reg_phd_solver.cpp.i
.PHONY : cpp/reg_phd_solver.cpp.i

cpp/reg_phd_solver.s: cpp/reg_phd_solver.cpp.s

.PHONY : cpp/reg_phd_solver.s

# target to generate assembly for a file
cpp/reg_phd_solver.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/reg_phd_solver.cpp.s
.PHONY : cpp/reg_phd_solver.cpp.s

cpp/reg_save_solver.o: cpp/reg_save_solver.cpp.o

.PHONY : cpp/reg_save_solver.o

# target to build an object file
cpp/reg_save_solver.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/reg_save_solver.cpp.o
.PHONY : cpp/reg_save_solver.cpp.o

cpp/reg_save_solver.i: cpp/reg_save_solver.cpp.i

.PHONY : cpp/reg_save_solver.i

# target to preprocess a source file
cpp/reg_save_solver.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/reg_save_solver.cpp.i
.PHONY : cpp/reg_save_solver.cpp.i

cpp/reg_save_solver.s: cpp/reg_save_solver.cpp.s

.PHONY : cpp/reg_save_solver.s

# target to generate assembly for a file
cpp/reg_save_solver.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/reg_save_solver.cpp.s
.PHONY : cpp/reg_save_solver.cpp.s

cpp/reg_seff_solver.o: cpp/reg_seff_solver.cpp.o

.PHONY : cpp/reg_seff_solver.o

# target to build an object file
cpp/reg_seff_solver.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/reg_seff_solver.cpp.o
.PHONY : cpp/reg_seff_solver.cpp.o

cpp/reg_seff_solver.i: cpp/reg_seff_solver.cpp.i

.PHONY : cpp/reg_seff_solver.i

# target to preprocess a source file
cpp/reg_seff_solver.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/reg_seff_solver.cpp.i
.PHONY : cpp/reg_seff_solver.cpp.i

cpp/reg_seff_solver.s: cpp/reg_seff_solver.cpp.s

.PHONY : cpp/reg_seff_solver.s

# target to generate assembly for a file
cpp/reg_seff_solver.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/reg_seff_solver.cpp.s
.PHONY : cpp/reg_seff_solver.cpp.s

cpp/reg_sir_solver.o: cpp/reg_sir_solver.cpp.o

.PHONY : cpp/reg_sir_solver.o

# target to build an object file
cpp/reg_sir_solver.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/reg_sir_solver.cpp.o
.PHONY : cpp/reg_sir_solver.cpp.o

cpp/reg_sir_solver.i: cpp/reg_sir_solver.cpp.i

.PHONY : cpp/reg_sir_solver.i

# target to preprocess a source file
cpp/reg_sir_solver.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/reg_sir_solver.cpp.i
.PHONY : cpp/reg_sir_solver.cpp.i

cpp/reg_sir_solver.s: cpp/reg_sir_solver.cpp.s

.PHONY : cpp/reg_sir_solver.s

# target to generate assembly for a file
cpp/reg_sir_solver.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/reg_sir_solver.cpp.s
.PHONY : cpp/reg_sir_solver.cpp.s

cpp/surv_dm_solver.o: cpp/surv_dm_solver.cpp.o

.PHONY : cpp/surv_dm_solver.o

# target to build an object file
cpp/surv_dm_solver.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/surv_dm_solver.cpp.o
.PHONY : cpp/surv_dm_solver.cpp.o

cpp/surv_dm_solver.i: cpp/surv_dm_solver.cpp.i

.PHONY : cpp/surv_dm_solver.i

# target to preprocess a source file
cpp/surv_dm_solver.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/surv_dm_solver.cpp.i
.PHONY : cpp/surv_dm_solver.cpp.i

cpp/surv_dm_solver.s: cpp/surv_dm_solver.cpp.s

.PHONY : cpp/surv_dm_solver.s

# target to generate assembly for a file
cpp/surv_dm_solver.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/surv_dm_solver.cpp.s
.PHONY : cpp/surv_dm_solver.cpp.s

cpp/surv_dn_solver.o: cpp/surv_dn_solver.cpp.o

.PHONY : cpp/surv_dn_solver.o

# target to build an object file
cpp/surv_dn_solver.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/surv_dn_solver.cpp.o
.PHONY : cpp/surv_dn_solver.cpp.o

cpp/surv_dn_solver.i: cpp/surv_dn_solver.cpp.i

.PHONY : cpp/surv_dn_solver.i

# target to preprocess a source file
cpp/surv_dn_solver.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/surv_dn_solver.cpp.i
.PHONY : cpp/surv_dn_solver.cpp.i

cpp/surv_dn_solver.s: cpp/surv_dn_solver.cpp.s

.PHONY : cpp/surv_dn_solver.s

# target to generate assembly for a file
cpp/surv_dn_solver.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/surv_dn_solver.cpp.s
.PHONY : cpp/surv_dn_solver.cpp.s

cpp/surv_forward_solver.o: cpp/surv_forward_solver.cpp.o

.PHONY : cpp/surv_forward_solver.o

# target to build an object file
cpp/surv_forward_solver.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/surv_forward_solver.cpp.o
.PHONY : cpp/surv_forward_solver.cpp.o

cpp/surv_forward_solver.i: cpp/surv_forward_solver.cpp.i

.PHONY : cpp/surv_forward_solver.i

# target to preprocess a source file
cpp/surv_forward_solver.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/surv_forward_solver.cpp.i
.PHONY : cpp/surv_forward_solver.cpp.i

cpp/surv_forward_solver.s: cpp/surv_forward_solver.cpp.s

.PHONY : cpp/surv_forward_solver.s

# target to generate assembly for a file
cpp/surv_forward_solver.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/surv_forward_solver.cpp.s
.PHONY : cpp/surv_forward_solver.cpp.s

cpp/utilities.o: cpp/utilities.cpp.o

.PHONY : cpp/utilities.o

# target to build an object file
cpp/utilities.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/utilities.cpp.o
.PHONY : cpp/utilities.cpp.o

cpp/utilities.i: cpp/utilities.cpp.i

.PHONY : cpp/utilities.i

# target to preprocess a source file
cpp/utilities.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/utilities.cpp.i
.PHONY : cpp/utilities.cpp.i

cpp/utilities.s: cpp/utilities.cpp.s

.PHONY : cpp/utilities.s

# target to generate assembly for a file
cpp/utilities.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_exports.dir/build.make CMakeFiles/cpp_exports.dir/cpp/utilities.cpp.s
.PHONY : cpp/utilities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cpp_exports"
	@echo "... cpp/cpp_exports.o"
	@echo "... cpp/cpp_exports.i"
	@echo "... cpp/cpp_exports.s"
	@echo "... cpp/gen_solver.o"
	@echo "... cpp/gen_solver.i"
	@echo "... cpp/gen_solver.s"
	@echo "... cpp/reg_local_solver.o"
	@echo "... cpp/reg_local_solver.i"
	@echo "... cpp/reg_local_solver.s"
	@echo "... cpp/reg_phd_solver.o"
	@echo "... cpp/reg_phd_solver.i"
	@echo "... cpp/reg_phd_solver.s"
	@echo "... cpp/reg_save_solver.o"
	@echo "... cpp/reg_save_solver.i"
	@echo "... cpp/reg_save_solver.s"
	@echo "... cpp/reg_seff_solver.o"
	@echo "... cpp/reg_seff_solver.i"
	@echo "... cpp/reg_seff_solver.s"
	@echo "... cpp/reg_sir_solver.o"
	@echo "... cpp/reg_sir_solver.i"
	@echo "... cpp/reg_sir_solver.s"
	@echo "... cpp/surv_dm_solver.o"
	@echo "... cpp/surv_dm_solver.i"
	@echo "... cpp/surv_dm_solver.s"
	@echo "... cpp/surv_dn_solver.o"
	@echo "... cpp/surv_dn_solver.i"
	@echo "... cpp/surv_dn_solver.s"
	@echo "... cpp/surv_forward_solver.o"
	@echo "... cpp/surv_forward_solver.i"
	@echo "... cpp/surv_forward_solver.s"
	@echo "... cpp/utilities.o"
	@echo "... cpp/utilities.i"
	@echo "... cpp/utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

